steps:
 # Build the container image
 - name: 'gcr.io/cloud-builders/docker'
   args: ['build', '-t', 'northamerica-northeast2-docker.pkg.dev/chatbase-b273c/frontend', '.']
 # Push the container image to Container Registry
 - name: 'gcr.io/cloud-builders/docker'
   args: ['push', 'northamerica-northeast2-docker.pkg.dev/chatbase-b273c/frontend']
 # Deploy container image to Cloud Run
 - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
   entrypoint: gcloud
   args:
   - 'run'
   - 'deploy'
   - 'frontend'
   - '--image'
   - 'northamerica-northeast2-docker.pkg.dev/chatbase-b273c/frontend'
   - '--region'
   - 'northamerica-northeast2'
   - '--port'
   - '8080'
options:
  logging: CLOUD_LOGGING_ONLY
images:
 - 'northamerica-northeast2-docker.pkg.dev/chatbase-b273c/frontend'
